import enum


class CreateChat(enum.Enum):

    COMMAND = "create_chat"
    RESPONSE_CHAT_NAME_EXISTS = "CHAT NAME IS NOT UNIQUE"
    RESPONSE_SECOND_USER_SPECIFIED = "YOU MUST SPECIFY SECOND USER"
    RESPONSE_SECOND_USER_NOT_FOUND = "SECOND USER DOES NOT EXIST"
    RESPONSE_CHAT_CREATED = "YOU CREATED CHAT"

    USER = 0
    ADMIN = 1

    PRIVATE = 0
    PUBLIC = 1
