import enum


class Misc:

    CLIENT = "client"
    SERVER = "server"


class Commands(enum.Enum):

    SIGN_IN = "sign_in"
    SIGN_UP = "sign_up"
    CREATE_CHAT = "create_chat"


class SignIn(enum.Enum):

    EXISTING_USER = "admin"
    EXISTING_PW = "adminadmin"
    NOT_EXISTING_USER = "NOTEXISTINGUSER"
    WRONG_PW = "WRONG_PW"

    RESPONSE_SUCCESSFULL_LOGIN = "SUCCESSFULLY LOGGED IN"
    RESPONSE_USER_NOT_FOUND = "USER NOT FOUND"
    RESPONSE_INCORRECT_PW = "INCORRECT PASSWORD"


class SignUP(enum.Enum):

    NEW_USER = "admin"
    CORRECT_PW = "adminadmin"
    INCORRECT_PW = " INCORRECT_PW"
    INCORRECT_LOGIN = " INCORRECT_LOGIN"

    RESPONSE_CONTENT_USER_EXISTS = "THIS LOGIN IS NOT UNIQUE"
    RESPONSE_CONTENT_SUCCESSFUL_SIGNUP = "REGISTRATION IS SUCCESSFUL"
    RESPONSE_CONTENT_INCORRECT_PW = "PASSWORD CANNOT START WITH A SPACE AND CONTAINS MORE THAN 50 CHARACTERS"
    RESPONSE_CONTENT_INCORRECT_LOGIN = "NICKNAME CANNOT START WITH A SPACE AND MUST CONTAINS ONLY 4 TO 16 CHARACTERS OF THE ENGLISH ALPHABET"


class Token(enum.Enum):

    VALID_TOKEN_LENGTH = 128
    EMPTY_TOKEN_LENGTH = 1
    EMPTY_TOKEN = "_"

    RESPONSE_NO_USER_IN_SESSION = "ERROR: NO SUCH USER SESSION"
    RESPONSE_TOKEN_AUTH_FAIL = "USER SESSION ERROR: TOKEN AUTH FAIL"


class Chat(enum.Enum):

    NAME = "TEST_CHAT"
    GROUP_CHAT_TYPE = 1

    RESPONSE_CHAT_CREATED = "CHAT WAS CREATED"
    RESPONSE_CHAT_NAME_EXISTS = "CHAT NAME IS NOT UNIQUE"

