import enum


class SignUP(enum.Enum):

    COMMAND = "sign_up"
    RESPONSE_INVALID_NICKNAME = "NICKNAME CANNOT START WITH A SPACE AND MUST CONTAINS ONLY 4 TO 16 CHARACTERS OF THE ENGLISH ALPHABET"
    RESPONSE_INVALID_PASSWORD = "PASSWORD CANNOT START WITH A SPACE AND CONTAINS MORE THAN 50 CHARACTERS"
    RESPONSE_LOGIN_EXISTS = "THIS LOGIN IS NOT UNIQUE"
    RESPONSE_REGISTRATION_SUCCESS = "REGISTRATION IS SUCCESSFUL"