import enum


class SignIn(enum.Enum):

    COMMAND = "sign_in"
    RESPONSE_SIGN_IN_SUCCESSFUL= "SUCCESSFULLY LOGGED IN"
    RESPONSE_USER_NOT_FOUND = "USER NOT FOUND"
    RESPONSE_INCORRECT_PASSWORD = "INCORRECT PASSWORD"


